###

# @name GetTypes
# @descrition Get the types of data available in the system.

GET http://localhost:3000/GetTypes?types=Emails,Chats,Sms
authorization: Bearer 123
accept: application/json
content-type: application/json

###

# @name TimeFilter
# @description Filter data based on time range and types.

POST http://localhost:3000/TimeFilter
authorization: Bearer 123
accept: application/json
content-type: application/json

{
  "DataTypes":[ "Chats", "Emails", "Sms" ],
  "FromTime":"2021-01-01T09:00",
  "ToTime":"2021-01-27T10:00"
}
